In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])

In [3]:
print(arr)

[1 2 3]


In [4]:
list_lists = [[1, 2, 3], [3, 4, 5], [4, 5, 6]]
arr = np.array(list_lists)

In [5]:
print(arr)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [6]:
lists = [1, 2, 3]

In [7]:
arr = np.array(lists)
print(arr)

[1 2 3]


In [8]:
np.arange(1, 10) # an array of integers from 1 to 9.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# do shift + tab to view the syntax

In [10]:
np.arange(1, 50, 5) # increase by 5 every time

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(10, int) # returns an array of zeros without floating point

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones((3, 4)) # (no of rows, no of columns)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0, 1, 5) #number of elements being 5. creates an array between the two extremes 0 and 1, with each element 
# differing by the same value

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.eye(5) # an identity matrix of 5*5 dimensions

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(3, 2)

array([[0.18600071, 0.52907104],
       [0.23959644, 0.48358374],
       [0.64664208, 0.15933964]])

In [18]:
np.random.randn(3, 2) # both pos and neg numbers are there.

array([[ 0.25805487,  0.68761455],
       [-0.03204773,  1.25764038],
       [ 1.36046625,  0.14489814]])

In [19]:
np.random.randint(1, 35) # returns a random integer in this range 1 to 34

1

In [20]:
np.random.randint(1, 34, 100) # 100 elements of random values from 1 to 33

array([ 5, 29, 21,  2, 25, 19,  5, 26,  6, 33, 26, 15,  2, 30, 12,  1,  8,
        9,  1, 13, 27,  1, 17,  4, 20, 18, 23,  7,  7, 29,  9,  4, 33, 20,
       14,  7, 14, 27, 15, 18,  3,  2,  8, 17, 10, 19, 28,  3, 26, 16,  2,
       23, 19, 29, 26, 18, 28, 29, 27,  8, 23, 32, 17,  2,  4,  6,  1,  8,
        3, 23, 24,  5, 17, 12, 21, 13, 28, 20, 21,  6, 30, 14, 30, 18, 24,
       28,  8, 10, 21, 11, 18, 25, 31, 27, 15,  2, 17, 15,  2, 30])

In [21]:
sample_array = np.arange(30)

In [22]:
sample_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
sample_array.reshape(6, 5) # makes the array a 6 * 5 matrix. the order can be observed from below. note that
# the number of rows * number of columns must be equal to the total number of elems.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [24]:
sample_array.reshape(3, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [25]:
random_array = np.random.randint(1, 35, 100)
random_array

array([ 5,  7, 27,  3, 14, 27, 30,  6, 31,  5, 34, 26, 18, 33, 16, 17, 24,
       20, 30, 27, 23, 33, 32, 32, 22, 30, 17, 19, 11, 19, 17, 15, 13, 10,
       20, 33,  5,  2, 14,  2, 32, 13, 14, 24,  2, 28, 17, 22, 25,  7,  2,
       15,  7,  9,  5, 23, 32, 33, 33, 10, 30, 21,  3, 34,  9, 31, 34, 14,
       33, 32, 30, 33, 24, 31,  4,  1, 25, 26,  4, 22, 31,  4, 21,  5,  3,
        8, 18, 18,  2,  5,  1,  9,  8, 28, 23,  9, 25, 18,  3, 13])

In [26]:
random_array.min()

1

In [27]:
random_array.argmin() # gives the index of the first min number.

75

In [28]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
sample_array[0:5] = 100

In [30]:
sample_array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

### Two Dimensional Array

In [31]:
sample_matrix = np.random.rand(4, 4)
sample_matrix

array([[0.3755919 , 0.77300608, 0.60449776, 0.26183237],
       [0.44876789, 0.43504134, 0.05445547, 0.90046458],
       [0.19539611, 0.97739769, 0.53860097, 0.9869096 ],
       [0.30181632, 0.59210918, 0.61093702, 0.4546556 ]])

In [32]:
sample_matrix[2, :]

array([0.19539611, 0.97739769, 0.53860097, 0.9869096 ])

In [33]:
sample_matrix[2]

array([0.19539611, 0.97739769, 0.53860097, 0.9869096 ])

In [34]:
sample_matrix[:, (3, 2)] # all rows and (3rd and 2nd) columns

array([[0.26183237, 0.60449776],
       [0.90046458, 0.05445547],
       [0.9869096 , 0.53860097],
       [0.4546556 , 0.61093702]])

In [35]:
# view rest of the functions such as unique(), max(), std(), var(), mean(), sqr(), etc.,  in the yHills course videos.

### Pandas

In [36]:
import pandas as pd

labels = ['w', "x", "y", "z"]
sample_list = [100, 200, 300, 400]

In [37]:
array = np.array([1, 2, 3, 4])
dict = {'w': 10, 'x': 20, 'y': 30, 'z': 40}

In [38]:
pd.Series(data = sample_list)

0    100
1    200
2    300
3    400
dtype: int64

In [39]:
pd.Series(data = sample_list, index = labels)

w    100
x    200
y    300
z    400
dtype: int64

In [40]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

In [41]:
sports1 = ['cricket', 'baseball', 'tennis']
sports2 = ['cricket', 'basketball', 'tennis']

sports1 = pd.Series([1, 2, 3], sports1)
sports2 = pd.Series([3, 2, 4], sports2)

In [42]:
sports1

cricket     1
baseball    2
tennis      3
dtype: int64

In [43]:
sports2

cricket       3
basketball    2
tennis        4
dtype: int64

In [44]:
sports1 + sports2

baseball      NaN
basketball    NaN
cricket       4.0
tennis        7.0
dtype: float64

In [45]:
df1 = pd.DataFrame(np.random.randn(8, 7), index = 'A B C D E F G H'.split(), columns = '1 2 3 4 5 6 7'.split())
df1

1         2         3         4         5         6         7
A -0.001043  2.179491 -1.862579 -0.931550 -0.403072  1.179337  1.340670
B  0.388849 -1.244421  0.577700  2.103855 -0.815763 -0.735658 -0.366169
C -0.017211 -1.618039  0.732811  0.387931 -1.796610 -0.688170  3.143122
D  0.164364 -0.519686 -0.283994  0.870127  0.466844  1.025610  1.741296
E  0.266445  0.597645  1.645511 -0.106349 -1.799034  0.419813 -0.805960
F -0.489156 -0.505934  1.534982  1.000495 -0.771324  0.812456  0.145376
G -1.241076  1.269570  0.351880 -2.487839 -0.299027  1.138405  1.307435
H -0.050866  0.416717 -1.339749  0.308829  0.432000  0.021936 -0.621955

### Importing Dataset using pandas

In [46]:
df = pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Financial-Analytics-Loan-Approval-Prediction/main/loan_prediction.csv")

In [47]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [48]:
df.head(10)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   
6  LP001013   Male     Yes          0  Not Graduate            No   
7  LP001014   Male     Yes         3+      Graduate            No   
8  LP001018   Male     Yes          2      Graduate            No   
9  LP001020   Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [49]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [50]:
df.sample()

Loan_ID  Gender Married Dependents Education Self_Employed  \
82  LP001267  Female     Yes          2  Graduate            No   

    ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
82             1378             1881.0       167.0             360.0   

    Credit_History Property_Area Loan_Status  
82             1.0         Urban           N

In [51]:
df.shape()


TypeError: 'tuple' object is not callable

In [52]:
df.shape

(614, 13)

In [53]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [55]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [56]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [57]:
df.describe(include = 'all')

Loan_ID Gender Married Dependents Education Self_Employed  \
count        614    601     611        599       614           582   
unique       614      2       2          4         2             2   
top     LP001002   Male     Yes          0  Graduate            No   
freq           1    489     398        345       480           500   
mean         NaN    NaN     NaN        NaN       NaN           NaN   
std          NaN    NaN     NaN        NaN       NaN           NaN   
min          NaN    NaN     NaN        NaN       NaN           NaN   
25%          NaN    NaN     NaN        NaN       NaN           NaN   
50%          NaN    NaN     NaN        NaN       NaN           NaN   
75%          NaN    NaN     NaN        NaN       NaN           NaN   
max          NaN    NaN     NaN        NaN       NaN           NaN   

        ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count        614.000000         614.000000  592.000000         600.00000   
unique              NaN                NaN         NaN               NaN   
top                 NaN                NaN         NaN               NaN   
freq                NaN                NaN         NaN               NaN   
mean        5403.459283        1621.245798  146.412162         342.00000   
std         6109.041673        2926.248369   85.587325          65.12041   
min          150.000000           0.000000    9.000000          12.00000   
25%         2877.500000           0.000000  100.000000         360.00000   
50%         3812.500000        1188.500000  128.000000         360.00000   
75%         5795.000000        2297.250000  168.000000         360.00000   
max        81000.000000       41667.000000  700.000000         480.00000   

        Credit_History Property_Area Loan_Status  
count       564.000000           614         614  
unique             NaN             3           2  
top                NaN     Semiurban           Y  
freq               NaN           233         422  
mean          0.842199           NaN         NaN  
std           0.364878           NaN         NaN  
min           0.000000           NaN         NaN  
25%           1.000000           NaN         NaN  
50%           1.000000           NaN         NaN  
75%           1.000000           NaN         NaN  
max           1.000000           NaN         NaN

#### Note: in df.drop(), the default axis is 0 (which is row). If a column must be dropped, use axis = 1