In [1]:
print("Hello World")

Hello World


### Python is Case-Sensitive

#### Writing with 4 Hashtags

# One Hashtag

In [2]:
Add a cell above -

SyntaxError: invalid syntax (Temp/ipykernel_23688/3743419509.py, line 1)

Add a cell above - a
Add a cell below - b
Delete a cell - x

In [3]:
''''''

''

##### Add a cell above - a
##### Add a cell below - b
##### Delete a cell - x


In [4]:
coursenames = "ds", 'ml'

### Numpy

#### Package for multidimensional arrays

In [3]:
import numpy as np

In [5]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [6]:
np.arrange(1, 100)

AttributeError: module 'numpy' has no attribute 'arrange'

In [7]:
np.arange(1, 100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### Note: It is arange and not arrange.

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(10, int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones(2, 5)

TypeError: Cannot interpret '5' as a data type

In [13]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.arange(1, 40, 5)

array([ 1,  6, 11, 16, 21, 26, 31, 36])

In [15]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])